/// Generated by AssetsRefGenerator on 2020/09/16
class Res {
  static const String coffin = "assets/images/coffin.png";
  static const String garlic = "assets/images/garlic.png";
  static const String group = "assets/images/group.png";
  static const String hospitalbed = "assets/images/hospitalbed.png";
  static const String lightningbolt = "assets/images/lightningbolt.png";
  static const String medicine = "assets/images/medicine.png";
  static const String patient = "assets/images/patient.png";
  static const String virus = "assets/images/virus.png";
}
